# Generated by Django 3.2.16 on 2025-09-18 05:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('description', models.TextField(blank=True, verbose_name='公司描述')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='职位要求')),
                ('level', models.CharField(max_length=100, verbose_name='职级')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='薪资范围')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviews.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='候选人姓名')),
                ('candidate_phone', models.CharField(max_length=20, verbose_name='候选人电话')),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='候选人邮箱')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('position_title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('position_description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('interview_method', models.CharField(choices=[('phone', '电话面试'), ('video', '视频面试'), ('onsite', '现场面试')], max_length=10, verbose_name='面试方式')),
                ('interview_round', models.CharField(choices=[('first', '初试'), ('second', '二面'), ('third', '三面'), ('final', '终面'), ('other', '其他轮次')], max_length=10, verbose_name='面试轮次')),
                ('scheduled_time', models.DateTimeField(verbose_name='面试时间')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='预计时长(分钟)')),
                ('interviewer_notes', models.TextField(blank=True, verbose_name='面试官备注')),
                ('status', models.CharField(choices=[('scheduled', '已安排'), ('in_progress', '面试中'), ('completed', '已完成'), ('cancelled', '已取消')], default='scheduled', max_length=20, verbose_name='状态')),
                ('result', models.CharField(choices=[('pending', '待定'), ('passed', '通过'), ('rejected', '未通过'), ('offer', '发放Offer'), ('declined', '已拒绝')], default='pending', max_length=20, verbose_name='面试结果')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='评分(1-100)')),
                ('feedback', models.TextField(blank=True, verbose_name='面试反馈')),
                ('recording', models.FileField(blank=True, null=True, upload_to='interview_recordings/%Y/%m/%d/', verbose_name='面试录音')),
                ('recording_uploaded', models.BooleanField(default=False, verbose_name='录音已上传')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.company', verbose_name='关联公司')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='面试官')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.jobposition', verbose_name='关联职位')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
