# Generated by Django 3.2.16 on 2025-09-19 01:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{17}[\\dXx]$', '请输入正确的身份证号码')], verbose_name='身份证号')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的手机号码')], verbose_name='学生电话')),
                ('father_phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的手机号码')], verbose_name='父亲电话')),
                ('mother_phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的手机号码')], verbose_name='母亲电话')),
                ('home_address', models.CharField(max_length=200, verbose_name='家庭住址')),
                ('education_level', models.CharField(choices=[('middle_school', '初中'), ('high_school', '高中'), ('secondary', '中专'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='当前学历')),
                ('graduation_date', models.DateField(verbose_name='毕业日期')),
                ('school_name', models.CharField(max_length=100, verbose_name='毕业院校')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('education_status', models.CharField(choices=[('studying', '在读'), ('graduated', '已毕业'), ('suspended', '休学'), ('dropped', '退学')], default='studying', max_length=20, verbose_name='在读状态')),
                ('project_manager', models.CharField(max_length=50, verbose_name='项目经理')),
                ('employment_guide', models.CharField(max_length=50, verbose_name='就业指导')),
                ('marketing_department', models.CharField(max_length=100, verbose_name='所属市场部')),
                ('certificates', models.TextField(blank=True, verbose_name='所持证书')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生基础信息',
                'verbose_name_plural': '学生基础信息',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('middle_school', '初中'), ('high_school', '高中'), ('secondary', '中专'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='学历')),
                ('graduation_date', models.DateField(verbose_name='毕业时间')),
                ('school_name', models.CharField(max_length=100, verbose_name='毕业院校')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_histories', to='interviews.studentinfo')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='证书名称')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
                ('issuing_authority', models.CharField(max_length=100, verbose_name='发证机构')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='证书编号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_list', to='interviews.studentinfo')),
            ],
            options={
                'verbose_name': '证书信息',
                'verbose_name_plural': '证书信息',
            },
        ),
    ]
